[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/new"
  to = "https://stackblitz.com/fork/node-8hobg2?file=test%2Fbasic.test.ts&view=editor"
  status = 302
